server:
  port: 8085
  
spring:
  application:
    name: config-service
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pragyasharma7796/micro-service-config
          clone-on-start: true