server:
  port: 8084
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    
spring:
  cloud:
    gateway:
      mvc:
        routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
             - path=/users/**
       
        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - path=/hotels/**
        
        
        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - path=/rating/**
       